[package]
name = "transports_py"
version = "0.1.2"
edition = "2021"
publish = false

[lib]
name = "transports"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
transports = { path = "./rust", version = "*" }
<<<<<<< before updating
pyo3 = { version = "0.26", features = ["abi3-py39", "extension-module", "multiple-pymethods"] }
strum = "0.27.2"
=======
pyo3 = { version = "0.27.1", features = ["abi3-py39", "extension-module", "multiple-pymethods"] }
>>>>>>> after updating

[profile.release]
panic = 'abort'
lto = true

[profile.test.junit]
path = "junit.xml"

[workspace]
members = [
    "js",
    "rust",
]
